function ImportFile(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 30-Aug-2014 22:23:16

% Import the file
newData1 = importdata(fileToRead1);

% Create new variables in the base workspace from those fields.
if ~strcmp(class(newData1),'uint8')
vars = fieldnames(newData1);
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end
else
    
    assignin('base', 'cdata', newData1);
end

